// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDreEjwvjtHLXEveUdX1SnF3S08mvakrmI',
    appId: '1:427055615890:web:068d61a87304005637bb4b',
    messagingSenderId: '427055615890',
    projectId: 'fproject-12409',
    authDomain: 'fproject-12409.firebaseapp.com',
    storageBucket: 'fproject-12409.appspot.com',
    measurementId: 'G-TQTNKC5C05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdJgJkLFFt-6Y3IwxE_UVdzt1_J4OmApI',
    appId: '1:427055615890:android:e2fb192442a93e0837bb4b',
    messagingSenderId: '427055615890',
    projectId: 'fproject-12409',
    storageBucket: 'fproject-12409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVDk9Sl8fc3CKMXyTvPc9pVWKVr7FF9bU',
    appId: '1:427055615890:ios:94075d0ba0b976a237bb4b',
    messagingSenderId: '427055615890',
    projectId: 'fproject-12409',
    storageBucket: 'fproject-12409.appspot.com',
    iosBundleId: 'com.example.flutterProjectt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVDk9Sl8fc3CKMXyTvPc9pVWKVr7FF9bU',
    appId: '1:427055615890:ios:99dd83a5d578122e37bb4b',
    messagingSenderId: '427055615890',
    projectId: 'fproject-12409',
    storageBucket: 'fproject-12409.appspot.com',
    iosBundleId: 'com.example.flutterProjectt.RunnerTests',
  );
}
